org: alsuepsm
app: apollo-lambda-app
# serverless.yml

service: zzan-api

# 우리가 사용할 함수에 최적화된 패키지를 생성합니다
package:
  indivitually: true

# plugins:
#   - serverless-bundle # 우리의 함수를 Webpack으로 패키징합니다

provider:
  name: aws
  region: us-east-2
  runtime: nodejs8.10
functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: src/index.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true